version: '2'

services: 
  app: 
    build: .
    volumes: 
      - ./code:/usr/src/app/
    ports:
      - 5000:5000
    #To Start Container in Bash Mode:
    stdin_open: true
    tty: true
    container_name: python-comp
    command: >
      bash -c "cd /usr/src/app/ && pip install -r requirements.txt && python"
  mysql:
    image: mysql:latest
    environment: 
        MYSQL_ROOT_PASSWORD: 'arschmin'
        MYSQL_DATABASE: 'test'
    ports: 
      - 3306:3306
    volumes: 
      - ./mysql-data:/var/lib/mysql
    
   
#docker exec -it <containername> bash
    