version: '2'

services: 
  app: 
    build: .
    volumes: 
      - ./code:/usr/src/app/
    ports:
      - 5000:5000
    #To Start Container in Bash Mode:
    stdin_open: true
    tty: true
    container_name: python-comp
    command: >
      bash -c "cd /usr/src/app/ && pip install -r requirements.txt && python"
   
#docker exec -it <containername> bash
    